


// user auth

export const FETCHING_CURRENT_USER = "FETCHING_CURRENT_USER"
export const FETCHED_CURRENT_USER_OK = "FETCHED_CURRENT_USER"
export const FETCHED_CURRENT_USER_FAIL = "FETCHED_CURRENT_USER_FAIL"

//feed
export const FETCHING_FEEDS = "FETCHING_FEEDS"
export const FETCHED_FEEDS_OK = "FETCHED_FEEDS_OK"
export const FETCHED_FEEDS_FAIL = "FETCHED_FEEDS_FAIL"
